#!/bin/bash
SD_AWS_USER="SD-Starter"
POLICY_NAME="SD-Starter-Policy"
POLICY_FILE="policy.json"

INSTANCE_NAME="SD-WEBUI-AUTO-1111"
AMI_ID="ami-026cbdd44856445d0"
INSTANCE_TYPE="g4dn.xlarge"
SECURITY_GROUP_NAME="SD-SG-AUTO-1111"

REGION="us-west-2"
KEY_NAME="SD-TEST-27-1"
KEY_FILE_PATH="SD-WEBUI-AUTO-1111.pem"
#KEY_FILE_PATH="SD-TEST.pem"

ACCESS_KEY_ID="XXXXXX"
SECRET_ACCESS_KEY="XXXXXXXX"
